name: Build and Compress

on:
  push:
    branches:
      - main # 你也可以根据需要改成任何你想监控的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: 设置 Node.js 版本
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # 可根据需要选择 Node.js 版本

      # Step 3: 安装依赖
      - name: Install dependencies
        run: npm install

      # Step 4: 运行 lint
      - name: Run lint
        run: npm run lint

      # Step 5: 运行 format
      - name: Run format
        run: npm run format

      # Step 6: 编译代码
      - name: Compile TypeScript
        run: npx tsc

      # Step 5: 删除所有 `.ts` 文件
      - name: Delete TypeScript files
        run: find . -name "*.ts" -type f -not -path "./node_modules/*" -exec rm -f {} +

      # Step 6: 压缩所有文件
      - name: Compress
        run: |
          tar -zcf dist.tar.gz main.ts config.json src/**/**/**/**/* init/**/**/**/**/* hazel/**/**/**/**/* config/**/**/**/**/* boot/**/**/**/**/*

      # Step 7: 上传到 GitHub Actions 的 artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: source
          path: dist.tar.gz

