name: Build Nexe Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build TypeScript
        run: npm run build

      - name: Build Nexe Executable
        run: npm run nexebuild

      - name: Upload Nexe Executable
        uses: actions/upload-artifact@v3
        with:
          name: crosst-chat-ts
          path: ./crosst-chat-ts
