name: Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: 安装依赖
      - name: Install dependencies
        run: |
          corepack enable
          echo y | yarn
          yarn install

      # Step 4: 运行 lint
      - name: Run lint
        run: npm run lint

      # Step 5: 运行 format
      - name: Run format
        run: npm run format

      # Step 6: 编译代码
      - name: Compile TypeScript
        run: npm run build

      # Step 3: 更改目录
      - name: Change directory
        run: cd dist

      - name: Copy yarn.lock from root
        run: cp ../yarn.lock .

      - name: Copy node_modules from root
        run: cp -r ../node_modules .

      - name: Copy package.json from root
        run: cp ../package.json .

      # Step 8: 复制文件
      - name: Copy files and compress
        run: |
          mkdir -p source
          find . -mindepth 1 -maxdepth 1 -not -name 'source' -exec cp -r {} source/ \;
          tar -zcf source.tar source
          gzip -r source.tar

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        with:
          files: source.tar.gz
          name: Release ${{ github.ref }}
          generate_release_notes: true
          tag_name: ${{ github.ref }}
          body: |
            Release for ${{ github.ref }}.
