name: Nightly Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run format
        run: npm run format

      - name: Compile TypeScript
        run: npx tsc

      - name: Delete TypeScript files
        run: find . -name "*.ts" -type f -not -path "./node_modules/*" -exec rm -f {} +

      - name: Generate source.tar.gz
        run: |
          mkdir -p source
          find . -mindepth 1 -maxdepth 1 -not -name 'source' -exec cp -r {} source/ \;
          tar -zcf source.tar source
          gzip -r source.tar

      - name: Generate release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: generate_notes
        run: |
          gh release delete nightly
          gh release create nightly -t "Nightly Release" source.tar.gz --generate-notes
